"""posts加入文章阅读数

Revision ID: 2dcbaba64d00
Revises: f4b0ed60ab45
Create Date: 2019-09-01 09:43:29.607896

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2dcbaba64d00'
down_revision = 'f4b0ed60ab45'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('posts', sa.Column('views_count', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('posts', 'views_count')
    # ### end Alembic commands ###
