"""加入大头像、小头像

Revision ID: ab767c974416
Revises: 3b5a012469cc
Create Date: 2019-08-26 11:56:46.486923

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'ab767c974416'
down_revision = '3b5a012469cc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('b_avatar', sa.String(length=128), nullable=True))
    op.add_column('users', sa.Column('s_avatar', sa.String(length=128), nullable=True))
    op.drop_column('users', 'avatar')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('avatar', mysql.VARCHAR(length=128), nullable=True))
    op.drop_column('users', 's_avatar')
    op.drop_column('users', 'b_avatar')
    # ### end Alembic commands ###
