"""加入文章摘要

Revision ID: dd74998d0061
Revises: dc488383107b
Create Date: 2019-08-26 16:02:55.198036

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'dd74998d0061'
down_revision = 'dc488383107b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('posts', sa.Column('abstract', sa.String(length=64), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('posts', 'abstract')
    # ### end Alembic commands ###
